# Generated by Django 5.0.6 on 2024-07-08 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_delete_company'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='email_is_verified',
            field=models.BooleanField(default=False),
        ),
    ]
