# Generated by Django 5.0.6 on 2024-07-08 17:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_profile_email_is_verified'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='email_is_verified',
        ),
    ]
