# Generated by Django 5.0.6 on 2024-07-08 17:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_remove_profile_email_is_verified'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='email_is_verified',
            field=models.BooleanField(default=False),
        ),
    ]
